# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36c3797b1744203012905a8a8f123076b95901421535ded82e01c83f900542876a11fbadc264b1f6677251bbe43d38b1650695c4b381b8a00853b39e683deb7a

test:
  secret_key_base: d22c5a712844027e0db104504b0ee8b5d00aa57f80478ed1552cc6ae596d67675e5f350e57cfc26241771ff916ed686ba0768a6d7cae00c35f241cd6eb300671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
